artifacts_root: artifacts


data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://github.com/AdMub/Wine-Quality-Prediction-End-to-End-Machine-Learning-with-MLflow-Project/raw/refs/heads/main/datasets/winequality-data.zip
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion